---
- hosts: controller
  sudo: yes
  vars:
  vars_files:
    - vars/junoConfiguration.yml
#   - osDetails: "--os-username {{ osUsername }} --os-password {{ osPassword }} --os-tenant-name {{ osTenantName }} --os-auth-url {{ osAuthUrl }} --os-region-name {{ osRegionName }} --os-tenant-id {{ osTenantID }}" 
  
  roles:
   - installPackages 
   - mysql
   - rabbitmq
   - keystone
   - glance
   - nova-controller
   - neutron-controller
#   - { role: createVolume, volume: "mysql", volumeSize: "{{mysqlVolumeSize}}", serverLocation: "{{ mysqlServerLocation }}"}
#   - { role: createVolume, volume: "elasticsearch", volumeSize: "{{elasticsearchVolumeSize}}", serverLocation: "{{ elasticsearchServerLocation }}"}
#   - { role: createVolume, volume: "cassandra", volumeSize: "{{cassandraVolumeSize}}", serverLocation: "{{ cassandraServerLocation }}"}
#   - { role: createVolume, volume: "registry", volumeSize: "{{registryVolumeSize}}", serverLocation: "{{ registryServerLocation }}"}
