---
# Node basic init
  - name: Remove 127.0.1.1 from hosts file.
    lineinfile: dest=/etc/hosts state=absent regexp="^127.0.1.1"
 
  - name: Install NTP package
    apt: name=ntp update_cache=no state=present

  - name: Configure ntp to work with controller node
    shell: echo "server {{controllerHostname}} iburst" > /etc/ntp.conf

  - name: Restart ntp service
    service: name=ntp state=restarted
      
  - name: Install Ubuntu cloud-keyring
    apt: name=ubuntu-cloud-keyring state=present
 
  - name: Add juno repository
    shell: echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu" "trusty-updates/juno main" > /etc/apt/sources.list.d/cloudarchive-juno.list
 
  - name: Update cache
    apt: 
       update_cache: yes 
       cache_valid_time: 600

  - name: Upgrade everything
    apt: 
       upgrade: dist 
       cache_valid_time: 600
